spring:
    application:
        name: jobportal
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/jobPortalSpring
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jackson:
        default-property-inclusion: NON_NULL
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    mail:
        host: smtp.gmail.com
        port: 587
        username: renaufalisnanto@gmail.com
        password: rmmxobmgzwktnvro
        default-encoding: UTF-8
        properties:
            smtp :
                auth: true
            mail :
                smtp:
                    starttls:
                        enable: true
springfox:
    documentation:
        swagger-ui:
            enabled: true
logging:
    level:
        org.springframework.security: TRACE
        org.springframework.validation: DEBUG
        org.springframework.web: DEBUG

discord:
  webhook:
    url: https://discord.com/api/webhooks/1311517417624834078/gbiTU9846RyjmQuWE_UNREdMm-HxMOD_6TcGwy-yUJDnPqASuqKGE0UM130epTl51C3d

